### ISSUE TITLE
[ WARNING ] Cannot create image for resizing.

### ISSUE THREAD

**Issue by mgrzeca** [VernissageApp/VernissageServer#31]
The above error occurs when attempting to upload certain images as an avatar or profile header. I'm attaching a sample avatar that triggers this error.

![428691_10201138668694664_1392948851_n](https://github.com/VernissageApp/VernissageServer/assets/2249297/0a5d2ada-2258-49b3-b116-5acea0f4b152)

**Comment by mczachurski** [comment]
Error occurs because this image is a PNG image but the extension is *.jpeg. When you rename file as .png or convert it to real .jpeg then everything is working.

The library for creating image in the memory cannot recognise that image as jpeg and returns exception. Maybe I can try first with user extension of the file and if library fails then I can rename it (from jpeg to png or from png to jpeg) and try again. But I'm not sure about this yet.

**Comment by mgrzeca** [comment]
OK, my bad...

Why won't you let the underlying image library detect the image type on its own?

<img width="857" alt="Zrzut ekranu 2024-04-10 o 11 34 18" src="https://github.com/VernissageApp/VernissageServer/assets/2249297/6bdd58d2-536e-4f9c-8e30-918b0a01b040">

**Comment by mczachurski** [comment]
I will try to figure out something here. I'm not sure that I want to support all of these types: bmp, gif, jpg, png, tiff, tga, wbmp, webp. On the other hand, it is better to support more than less 🤔.
