### ISSUE TITLE
User handles with a domain part different from the instance hostname are not handled properly

### ISSUE THREAD

**Issue by mgrzeca** [VernissageApp/VernissageServer#55]
I can see two cases.

One is simply displayed incorrectly; so far, I haven't noticed any other related issues. Below is an example:

<img width="662" alt="Zrzut ekranu 2024-04-19 o 12 51 18" src="https://github.com/VernissageApp/VernissageServer/assets/2249297/27c8d135-6587-4c0e-89c3-2145f5adbd3e">

 In some cases, it's impossible to find such a user. Example:

<img width="662" alt="Zrzut ekranu 2024-04-19 o 12 51 45" src="https://github.com/VernissageApp/VernissageServer/assets/2249297/b7a2bc79-9548-4ca8-8267-eb9bf4eec5c0">

In this second case, nothing gets logged.

**Comment by mczachurski** [comment]
The issue was because that specific instance has different username domain (mkljczk@fediverse.pl) and different domain where web finger profile is available (https://pl.fediverse.pl/.well-known/webfinger?resource=mkljczk@fediverse.pl).

Now before searching for the profile I'm always getting link to web finger from host-meta endpoint. For that instance we have (URL: https://fediverse.pl/.well-known/host-meta):

```xml
<?xml version="1.0" encoding="UTF-8"?>
<XRD xmlns="http://docs.oasis-open.org/ns/xri/xrd-1.0">
    <Link type="application/xrd+xml" template="https://pl.fediverse.pl/.well-known/webfinger?resource={uri}" rel="lrdd" />
</XRD>
```
